- hosts: terraform-ansible
  become: yes

  vars:
    myvars:
      MYSQL_ROOT_PASSWORD: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
      DATASOURCE_USERNAME: "{{ lookup('env', 'MYSQL_USER') }}"
      DATASOURCE_PASSWORD: "{{ lookup('env', 'MYSQL_PASSWORD') }}"
      MYSQL_DATABASE: "{{ lookup('env', 'MYSQL_DATABASE') }}"
      DB_PORT: "3306"

  tasks:
  - name: update e upgrade packages
    apt:
      update_cache: yes

  - name: installing docker dependencies
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

  - name: adding Docker GPG Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: adding Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
      state: present

  - name: installing docker
    apt:
      name: docker-ce
      state: present
  
  - name: installing python3, pip
    apt:
      name:
        - python3
        - python3-pip
      state: present

  - name: installing docker through pip 
    pip:
      name: docker==2.7
      state: present
  
  - name: adding all environment variables
    lineinfile:
      path: /etc/environment
      line: "{{item.key}}={{item.value}}"
    with_dict: "{{ myvars }}"
  
  - name: adding db_url environment variable
    lineinfile:
      path: /etc/environment
      line: "DATASOURCE_URL=jdbc:mysql://localhost:{{ myvars.DB_PORT }}/{{ myvars.MYSQL_DATABASE }}"

  - name: creating mysql container
    docker_container:
      name: mysql
      image: mysql
      env:
        MYSQL_ROOT_PASSWORD: "{{ myvars.MYSQL_ROOT_PASSWORD }}"
        MYSQL_USER: "{{ myvars.DATASOURCE_USERNAME }}"
        MYSQL_PASSWORD: "{{ myvars.DATASOURCE_PASSWORD }}"
        MYSQL_DATABASE: "{{ myvars.MYSQL_DATABASE }}"
      ports:
        - "{{ myvars.DB_PORT }}:3306"
      auto_remove: yes

  - name: installing git
    apt:
      name: git
      state: present
  
  - name: clone the project
    git:
      repo: "https://github.com/rcaneppele/2771-spring-boot.git"
      dest: "/home/ubuntu/challenge-devops"
      update: yes
  
  - name: install maven and jdk
    apt:
      name:
        - maven
        - openjdk-17-jdk
      state: present
  
  - name: build maven project
    command: mvn clean package
    args:
      chdir: "/home/ubuntu/challenge-devops"
  

